development:
  TWILIO_ACCOUNT_SID: "ACd0b3eca7503143f7fe5732fcc0eacb03"
  TWILIO_AUTH_TOKEN: "e349a6f7adfb13bee755d339c027eefe"
  MY_TWILIO_NUMBER: "+13122486056"
  TWITTER_CONSUMER_KEY: "7g2NbMkBGJhyoD77lFGLNHPeh"
  TWITTER_CONSUMER_SECRET: "P8HEGsnRf2Eq7NSDVYIf1D6qEwbgVtocrOOetzW9feZiRPJRnc"
  TWITTER_ACCESS_TOKEN: "67340686-wvdzION8So1RsUfMwkJD9clsupouzNrIX3FcwZPyt"
  TWITTER_ACCESS_SECRET: "6TSVe5vMTLISm1mUI20svVFTc0j2i3CmWlaWAUjDZxHkT"
  TWITTER_USERNAME: "Rishabh_Tayal"
  MY_PHONE_NUMBER: "+13095315212"